// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tmnwlfpziceunkquiwgp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRtbndsZnB6aWNldW5rcXVpd2dwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0MDc0MzAsImV4cCI6MjA2Mzk4MzQzMH0.mh8d9WGvEHjy80sAaoG85XPueXEEqUzmRuLXyevSfFo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);